Pandas is an open-source python library for data analysis and manipulation. It provides data structures like Series and Dataframe for handling structured data

1. **Installing and Importing Pandas**

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
pd.__version__   # check installed pandas version

'2.2.2'

2. **Data Structures in Pandas**

2.1. Series (One-Dimensional Data): A Series is like a single column in Excel.

In [ ]:
marks = pd.Series([85, 90, 78, 92])
marks

0    85
1    90
2    78
3    92
dtype: int64

series with labels

In [ ]:
marks = pd.Series([85, 90, 78, 92], index=['Math', 'Science', 'English', 'CS'])
marks

Math       85
Science    90
English    78
CS         92
dtype: int64

2.2. DataFrame (Two-Dimensional Data): A DataFrame is like a table with rows and columns.

In [ ]:
students = pd.DataFrame({
    'Name': ['Amit', 'Riya', 'John'],
    'Age': [21, 22, 20],
    'Marks': [85, 90, 88]
})

students

   Name  Age  Marks
0  Amit   21     85
1  Riya   22     90
2  John   20     88

**3. Basic Pandas Commands**

3.1 Viewing Data

In [ ]:
students.head()      # First 5 rows

   Name  Age  Marks
0  Amit   21     85
1  Riya   22     90
2  John   20     88

In [ ]:
students.tail()      # Last 5 rows

   Name  Age  Marks
0  Amit   21     85
1  Riya   22     90
2  John   20     88

In [ ]:
students.shape       # Rows, Columns

(3, 3)

In [ ]:
students.columns     # Column names

Index(['Name', 'Age', 'Marks'], dtype='object')

In [ ]:
students.index       # Row index

RangeIndex(start=0, stop=3, step=1)

3.2 Information About Data

In [ ]:
students.info()      # Data types & missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [ ]:
students.describe()  # Statistical summary

        Age      Marks
count   3.0   3.000000
mean   21.0  87.666667
std     1.0   2.516611
min    20.0  85.000000
25%    20.5  86.500000
50%    21.0  88.000000
75%    21.5  89.000000
max    22.0  90.000000

3.3 Selecting Data

In [ ]:
students['Name']           # Single column

0    Amit
1    Riya
2    John
Name: Name, dtype: object

In [ ]:
students[['Name','Marks']]# Multiple columns

   Name  Marks
0  Amit     85
1  Riya     90
2  John     88

3.4 Adding & Removing Columns

In [ ]:
students['Passed'] = students['Marks'] > 80
students

   Name  Age  Marks  Passed
0  Amit   21     85    True
1  Riya   22     90    True
2  John   20     88    True

In [ ]:
students.drop('Age', axis=1, inplace=True)
students

   Name  Marks  Passed
0  Amit     85    True
1  Riya     90    True
2  John     88    True

3.5 .loc and .iloc (Row selection)

In [ ]:
df_ = pd.DataFrame(
    {
        'Product': ['Pen', 'Notebook', 'Pencil', 'Eraser'],
        'Price': [10, 50, 5, 8],
        'Quantity': [100, 40, 200, 150]
    },
    index=['P1', 'P2', 'P3', 'P4']
)

df_

     Product  Price  Quantity
P1       Pen     10       100
P2  Notebook     50        40
P3    Pencil      5       200
P4    Eraser      8       150

In [ ]:
print(df_.loc['P1'])                 # Product with ID P1
print(df_.loc['P2':'P3'])            # Products P2 and P3
print(df_.loc[['P1', 'P4']])         # Selected products
print(df_.loc['P3', 'Price'])        # Price of P3
print(df_.loc[:, 'Quantity'])        # Quantity column

Product     Pen
Price        10
Quantity    100
Name: P1, dtype: object
     Product  Price  Quantity
P2  Notebook     50        40
P3    Pencil      5       200
   Product  Price  Quantity
P1     Pen     10       100
P4  Eraser      8       150
5
P1    100
P2     40
P3    200
P4    150
Name: Quantity, dtype: int64

In [ ]:
print(df_.iloc[0])            # First product
print(df_.iloc[1:3])            # Products at pos 1 and 2
print(df_.iloc[[0, 3]])       # First and last products
print(df_.iloc[2, 1])         #  Price at pos (2,1)
print(df_.iloc[:, 1])         # Price column

Product     Pen
Price        10
Quantity    100
Name: P1, dtype: object
     Product  Price  Quantity
P2  Notebook     50        40
P3    Pencil      5       200
   Product  Price  Quantity
P1     Pen     10       100
P4  Eraser      8       150
5
P1    10
P2    50
P3     5
P4     8
Name: Price, dtype: int64

.loc  → uses labels → end index included

.iloc → uses numbers → end index excluded

Use .loc when you know the name of the data, and .iloc when you know the position.

3.5 Reading and Writing Files

In [ ]:
df = pd.read_csv('data.csv')
df = pd.read_excel('data.xlsx')

In [ ]:
df.to_csv('output.csv', index=False)
df.to_excel('output.xlsx', index=False)

4. **Handling Missing Values (NaN / NA)**

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Name': ['A', 'B', 'C'],
    'Age': [22, np.nan, 25],
    'Salary': [30000, 40000, np.nan]
}

df_2= pd.DataFrame(data)
df_2

  Name   Age   Salary
0    A  22.0  30000.0
1    B   NaN  40000.0
2    C  25.0      NaN

Identify missing values

In [ ]:
df_2.isna()  #Returns True where data is missing.

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True

Count missing values column-wise

In [ ]:
df_2.isna().sum()

Name      0
Age       1
Salary    1
dtype: int64

In [ ]:
df_2.dropna()    #Drop rows containing missing values

  Name   Age   Salary
0    A  22.0  30000.0

Fill Missing Values

In [ ]:
df_2['Age'].fillna(df_2['Age'].mean(), inplace=True)   #Fill Age with Mean

/tmp/ipython-input-4216819810.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_2['Age'].fillna(df_2['Age'].mean(), inplace=True)   #Fill Age with Mean

In [ ]:
df_2['Salary'].fillna(0, inplace=True)   #Fill Salary with 0
df_2

/tmp/ipython-input-1502484670.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_2['Salary'].fillna(0, inplace=True)   #Fill Salary with 0

  Name   Age   Salary
0    A  22.0  30000.0
1    B  23.5  40000.0
2    C  25.0      0.0

**5. GroupBy**

GroupBy is used to: Split data into groups, Apply a function (mean, sum, count), Combine results

In [ ]:
data = {
    'Dept': ['IT', 'IT', 'HR', 'HR'],
    'Salary': [50000, 60000, 45000, 48000]
}

df_emp= pd.DataFrame(data)
df_emp

  Dept  Salary
0   IT   50000
1   IT   60000
2   HR   45000
3   HR   48000

In [ ]:
df_emp.groupby('Dept')['Salary'].mean()     #Average Salary per Department

Dept
HR    46500.0
IT    55000.0
Name: Salary, dtype: float64

In [ ]:
df_emp.groupby('Dept').agg(                          #Multiple Aggregations
    MinSalary=('Salary', 'min'),
    MaxSalary=('Salary', 'max'),
    AvgSalary=('Salary', 'mean')
)SQL query to a relational database

      MinSalary  MaxSalary  AvgSalary
Dept
HR        45000      48000    46500.0
IT        50000      60000    55000.0

6. **Merge and Join**

In real-world data, information is stored in multiple tables.
merge() combines them like SQL JOIN.

In [ ]:
emp = pd.DataFrame({
    'EmpID': [1, 2, 3],
    'Name': ['Amit', 'Riya', 'John']
})

dept = pd.DataFrame({
    'EmpID': [1, 2, 3],
    'Department': ['IT', 'HR', 'Finance']
})

In [ ]:
pd.merge(emp, dept, on='EmpID')  #Merge on Common Column

   EmpID  Name Department
0      1  Amit         IT
1      2  Riya         HR
2      3  John    Finance

In [ ]:
pd.merge(emp, dept, how='left', on='EmpID')  #Left Join

   EmpID  Name Department
0      1  Amit         IT
1      2  Riya         HR
2      3  John    Finance

In [ ]:
pd.merge(emp, dept, how='outer', on='EmpID')   #outer join

   EmpID  Name Department
0      1  Amit         IT
1      2  Riya         HR
2      3  John    Finance

https://www.geeksforgeeks.org/python/different-types-of-joins-in-pandas/  - Please refer to this link for more details on joins.

7. **Time-Series Data in Pandas**

Data indexed by date or time (sales, stock prices, temperature).Pandas has built-in support for time-series analysis.

In [ ]:
dates = pd.date_range('2024-01-01', periods=5)

sales = pd.Series([100, 120, 90, 150, 200], index=dates)
sales

2024-01-01    100
2024-01-02    120
2024-01-03     90
2024-01-04    150
2024-01-05    200
Freq: D, dtype: int64

In [ ]:
sales['2024-01-02':'2024-01-04']    #Date-Based Selection

2024-01-02    120
2024-01-03     90
2024-01-04    150
Freq: D, dtype: int64

In [ ]:
sales.resample('M').sum()           #Converts daily data to monthly summary.

/tmp/ipython-input-2362657547.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  sales.resample('M').sum()           #Converts daily data to monthly summary.

2024-01-31    660
Freq: ME, dtype: int64

8. Window function

Window functions perform calculations on a moving window of data.

Used for: Moving averages, Trend analysis, Smoothing data

In [ ]:
sales.rolling(window=2).mean()   #Rolling Mean (Moving Average)
                                 #Each value is the average of the previous 2 values.

2024-01-01      NaN
2024-01-02    110.0
2024-01-03    105.0
2024-01-04    120.0
2024-01-05    175.0
Freq: D, dtype: float64

In [ ]:
sales.expanding().mean()          #Expanding Mean
                                  #Average from start until current row.

2024-01-01    100.000000
2024-01-02    110.000000
2024-01-03    103.333333
2024-01-04    115.000000
2024-01-05    132.000000
Freq: D, dtype: float64

In [ ]:
sales.ewm(span=2).mean()           #Exponential Moving Average (EMA)
                                   #Gives more weight to recent values.

2024-01-01    100.000000
2024-01-02    115.000000
2024-01-03     97.692308
2024-01-04    133.000000
2024-01-05    177.851240
Freq: D, dtype: float64

9. **Complete ETL Example Using Pandas**

9.1 Extract-Load Raw Data into DataFrame

In [ ]:
import pandas as pd
import numpy as np

data = {
    'EmpID': [101,102,103,104,105,106,107,108,109,110,111,112,113,114,115],
    'Name': ['Amit','Riya','John','Neha','Raj','Kiran','Anu','Vijay','Pooja','Sam','Arjun','Meena','Rohit','Sara','Dev'],
    'Department': ['IT','HR','IT','Finance','HR','IT','Finance','IT','HR','IT','Finance','HR','IT','Finance','HR'],
    'Age': [25, np.nan, 30, 28, 35, 26, np.nan, 29, 31, 27, 34, np.nan, 28, 32, 26],
    'Salary': [50000, 45000, np.nan, 55000, 48000, 52000, 51000, np.nan, 47000, 54000, 60000, 46000, np.nan, 58000, 49000],
    'JoiningDate': ['2022-01-10','2022-03-15','', '2021-07-01','2020-06-20',
                    '2022-02-18','2021-09-12','', '2023-01-05','2022-11-25',
                    '2020-04-10','', '2023-03-15','2021-12-01','2022-08-30']
}

emp_details= pd.DataFrame(data)
emp_details

    EmpID   Name Department   Age   Salary JoiningDate
0     101   Amit         IT  25.0  50000.0  2022-01-10
1     102   Riya         HR   NaN  45000.0  2022-03-15
2     103   John         IT  30.0      NaN
3     104   Neha    Finance  28.0  55000.0  2021-07-01
4     105    Raj         HR  35.0  48000.0  2020-06-20
5     106  Kiran         IT  26.0  52000.0  2022-02-18
6     107    Anu    Finance   NaN  51000.0  2021-09-12
7     108  Vijay         IT  29.0      NaN
8     109  Pooja         HR  31.0  47000.0  2023-01-05
9     110    Sam         IT  27.0  54000.0  2022-11-25
10    111  Arjun    Finance  34.0  60000.0  2020-04-10
11    112  Meena         HR   NaN  46000.0
12    113  Rohit         IT  28.0      NaN  2023-03-15
13    114   Sara    Finance  32.0  58000.0  2021-12-01
14    115    Dev         HR  26.0  49000.0  2022-08-30

9.2 Transform- Clean and Process the Data

Understand the Data

In [ ]:
emp_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmpID        15 non-null     int64
 1   Name         15 non-null     object
 2   Department   15 non-null     object
 3   Age          12 non-null     float64
 4   Salary       12 non-null     float64
 5   JoiningDate  15 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 852.0+ bytes

Handle Missing Age Values

In [ ]:
emp_details['Age'].fillna(emp_details['Age'].mean(), inplace=True)

/tmp/ipython-input-1720215485.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  emp_details['Age'].fillna(emp_details['Age'].mean(), inplace=True)

In [ ]:
emp_details['Salary'].fillna(emp_details['Salary'].median(), inplace=True)

/tmp/ipython-input-4096225268.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  emp_details['Salary'].fillna(emp_details['Salary'].median(), inplace=True)

Clean Joining Date Column

In [ ]:
emp_details['JoiningDate'].replace('', np.nan, inplace=True)
emp_details['JoiningDate'].fillna('2022-01-01', inplace=True)
emp_details['JoiningDate'] = pd.to_datetime(emp_details['JoiningDate'])

/tmp/ipython-input-1124382238.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  emp_details['JoiningDate'].replace('', np.nan, inplace=True)
/tmp/ipython-input-1124382238.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  emp_details['JoiningDate'].fillna('2022-01-01', inplace=True)

In [ ]:
emp_details.head()

   EmpID  Name Department    Age   Salary JoiningDate
0    101  Amit         IT  25.00  50000.0  2022-01-10
1    102  Riya         HR  29.25  45000.0  2022-03-15
2    103  John         IT  30.00  50500.0  2022-01-01
3    104  Neha    Finance  28.00  55000.0  2021-07-01
4    105   Raj         HR  35.00  48000.0  2020-06-20

Standardize Department Names

In [ ]:
emp_details['Department'] = emp_details['Department'].str.upper()

Create New Columns

In [ ]:
emp_details['AnnualSalary'] = emp_details['Salary'] * 12

In [ ]:
emp_details.head()

   EmpID  Name Department    Age   Salary JoiningDate  AnnualSalary
0    101  Amit         IT  25.00  50000.0  2022-01-10      600000.0
1    102  Riya         HR  29.25  45000.0  2022-03-15      540000.0
2    103  John         IT  30.00  50500.0  2022-01-01      606000.0
3    104  Neha    FINANCE  28.00  55000.0  2021-07-01      660000.0
4    105   Raj         HR  35.00  48000.0  2020-06-20      576000.0

Rename Columns for Clarity

In [ ]:
emp_details.rename(columns={'JoiningDate': 'DOJ'}, inplace=True)

In [ ]:
emp_details.head()

   EmpID  Name Department    Age   Salary        DOJ  AnnualSalary
0    101  Amit         IT  25.00  50000.0 2022-01-10      600000.0
1    102  Riya         HR  29.25  45000.0 2022-03-15      540000.0
2    103  John         IT  30.00  50500.0 2022-01-01      606000.0
3    104  Neha    FINANCE  28.00  55000.0 2021-07-01      660000.0
4    105   Raj         HR  35.00  48000.0 2020-06-20      576000.0

9.3 Load- Save the Cleaned Data

In [ ]:
emp_details.to_csv("employees_cleaned.csv", index=False)

10. SQL with Pandas

Pandas allows us to: Write SQL queries, Fetch results directly into a DataFrame, Combine the power of SQL + Python analysis

Required Libraries

In [1]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.45)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

Connect Pandas to a Relational Database

In [5]:
from sqlalchemy import create_engine

**SQL lite**

In [6]:
engine = create_engine("sqlite:///company.db")

Reading SQL Data into Pandas

In [ ]:
df = pd.read_sql("SELECT * FROM employees", engine)             #Read Entire Table
df

In [ ]:
pd.read_sql(
    "SELECT Name, Salary FROM employees",                       #Select Specific Column
    engine
)

In [ ]:
pd.read_sql(
    "SELECT * FROM employees WHERE Dept = 'IT'",                #Filter rows
    engine
)

In [ ]:
pd.read_sql(
    "SELECT * FROM employees ORDER BY Salary DESC",            #sort result
    engine
)

In [ ]:
df.to_sql(
    'employees_processed',
    engine,                                                  #writing back to databases
    if_exists='replace',
    index=False
)

**MySQL**

In [ ]:
pip install pymysql

In [ ]:
engine = create_engine(
    "mysql+pymysql://username:password@localhost:3306/company"
)

**PostgreSQL**

In [ ]:
pip install psycopg2-binary

In [ ]:
engine = create_engine(
    "postgresql+psycopg2://username:password@localhost:5432/company"
)

**SQL Server**

In [ ]:
pip install pyodbc

In [ ]:
engine = create_engine(
    "mssql+pyodbc://username:password@servername/database"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)